name: publish
run-name: ${{ github.actor }} is publishing 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      # - run: xvfb-run -a npm test
      #   if: runner.os == 'Linux'
      # - run: npm test
      #   if: runner.os != 'Linux'
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
